services:

  pg:
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-psyco_tests}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
#    networks:
#      - some
    volumes:
      - pg_data:/var/lib/postgresql/data

#networks:
#  some:
#    external: false
#    driver: bridge

volumes:
  pg_data:
  media_files:
