"""added media to the question

Revision ID: 21d84743bedf
Revises: 8236c133acb0
Create Date: 2024-10-01 16:04:56.717046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from fastapi_storages.integrations.sqlalchemy import FileType
from services import movie_quiz_storage


# revision identifiers, used by Alembic.
revision: str = '21d84743bedf'
down_revision: Union[str, None] = '8236c133acb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_quizzes', sa.Column('picture', FileType(storage=movie_quiz_storage), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_quizzes', 'picture')
    # ### end Alembic commands ###
