"""added a fact field to the question and to the quiz

Revision ID: 68e658899aac
Revises: 21d84743bedf
Create Date: 2024-10-01 16:21:38.155670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from fastapi_storages.integrations.sqlalchemy import FileType
from services import movie_quiz_storage


# revision identifiers, used by Alembic.
revision: str = '68e658899aac'
down_revision: Union[str, None] = '21d84743bedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_quiz_questions', sa.Column('picture', FileType(storage=movie_quiz_storage), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_quiz_questions', 'picture')
    # ### end Alembic commands ###
