"""create psyco tests tables2

Revision ID: ba0316f91e42
Revises: 364d71f1d1c9
Create Date: 2024-10-02 02:08:48.752197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba0316f91e42'
down_revision: Union[str, None] = '364d71f1d1c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psyco_answers_with_correct_marker', sa.Column('question_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_psyco_answers_with_correct_marker_question_id_psyco_questions_with_correct_answer'), 'psyco_answers_with_correct_marker', 'psyco_questions_with_correct_answer', ['question_id'], ['id'])
    op.add_column('psyco_questions_with_correct_answer', sa.Column('test_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_psyco_questions_with_correct_answer_test_id_pyco_tests_with_correct_answer'), 'psyco_questions_with_correct_answer', 'pyco_tests_with_correct_answer', ['test_id'], ['id'])
    op.add_column('psyco_results_with_from_to_group', sa.Column('test_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_psyco_results_with_from_to_group_test_id_pyco_tests_with_correct_answer'), 'psyco_results_with_from_to_group', 'pyco_tests_with_correct_answer', ['test_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_psyco_results_with_from_to_group_test_id_pyco_tests_with_correct_answer'), 'psyco_results_with_from_to_group', type_='foreignkey')
    op.drop_column('psyco_results_with_from_to_group', 'test_id')
    op.drop_constraint(op.f('fk_psyco_questions_with_correct_answer_test_id_pyco_tests_with_correct_answer'), 'psyco_questions_with_correct_answer', type_='foreignkey')
    op.drop_column('psyco_questions_with_correct_answer', 'test_id')
    op.drop_constraint(op.f('fk_psyco_answers_with_correct_marker_question_id_psyco_questions_with_correct_answer'), 'psyco_answers_with_correct_marker', type_='foreignkey')
    op.drop_column('psyco_answers_with_correct_marker', 'question_id')
    # ### end Alembic commands ###
