"""add pictures to tests

Revision ID: bf9c6881a679
Revises: d48e381859f0
Create Date: 2024-10-03 02:41:16.077835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from fastapi_storages.integrations.sqlalchemy import FileType
from services import psyco_test_storage


# revision identifiers, used by Alembic.
revision: str = 'bf9c6881a679'
down_revision: Union[str, None] = 'd48e381859f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psyco_tests', sa.Column('picture', FileType(psyco_test_storage), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psyco_tests', 'picture')
    # ### end Alembic commands ###
