"""upd test model to aviod diff logic

Revision ID: c675d188c784
Revises: 79ca3d7562e4
Create Date: 2024-10-02 21:43:14.608220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c675d188c784'
down_revision: Union[str, None] = '79ca3d7562e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('psyco_question_answers', 'is_correct')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psyco_question_answers', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
