"""create tests with score logic

Revision ID: c900c9bc32cb
Revises: ba0316f91e42
Create Date: 2024-10-02 15:52:32.744817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c900c9bc32cb'
down_revision: Union[str, None] = 'ba0316f91e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psyco_tests_with_score_answers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_psyco_tests_with_score_answers'))
    )
    op.create_table('psyco_questions_with_score_answers',
    sa.Column('question_text', sa.String(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['psyco_tests_with_score_answers.id'], name=op.f('fk_psyco_questions_with_score_answers_test_id_psyco_tests_with_score_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_psyco_questions_with_score_answers'))
    )
    op.create_table('psyco_results_with_score_group',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['psyco_tests_with_score_answers.id'], name=op.f('fk_psyco_results_with_score_group_test_id_psyco_tests_with_score_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_psyco_results_with_score_group'))
    )
    op.create_table('psyco_answers_with_score_marker',
    sa.Column('answer_text', sa.String(), nullable=False),
    sa.Column('score_value', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['psyco_questions_with_score_answers.id'], name=op.f('fk_psyco_answers_with_score_marker_question_id_psyco_questions_with_score_answers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_psyco_answers_with_score_marker'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psyco_answers_with_score_marker')
    op.drop_table('psyco_results_with_score_group')
    op.drop_table('psyco_questions_with_score_answers')
    op.drop_table('psyco_tests_with_score_answers')
    # ### end Alembic commands ###
